## Practice 1: Creating DataFrames and Series

**Q1.** Create a Pandas Series from a list of numbers: `[10, 20, 30, 40, 50]`.

In [83]:
import pandas as pd
listt = pd.Series([10,20,30,40,50])
listt

0    10
1    20
2    30
3    40
4    50
dtype: int64

**Q2.** Create a Pandas DataFrame from the following dictionary:
```python
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
```

In [84]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
fromdict = pd.DataFrame(data)
fromdict

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 2: Inspecting Data

**Q3.** Given the DataFrame `df`, display the first 3 rows.
```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
```

In [85]:
import pandas as pd
import numpy as np
df2 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2.head(3)

          A         B         C         D
0 -0.409021 -1.349937 -1.641980 -1.394722
1 -0.089907 -0.059002 -0.161582  1.594191
2  1.101022 -0.874784 -2.383967  0.481743

**Q4.** Print the shape and column names of the DataFrame `df2`.

In [86]:
print(df2.shape)
print(df2.columns.tolist())

(10, 4)
['A', 'B', 'C', 'D']

## Practice 3: Selecting and Filtering

**Q5.** Select the column 'Age' from the DataFrame created in Q2 (`df`).

In [87]:
fromdict["Age"]

0    25
1    30
2    35
Name: Age, dtype: int64

**Q6.** Filter the DataFrame `df` from Q2 to show only rows where 'Age' is greater than 28.

In [88]:
fromdict[fromdict["Age"] > 28]

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 4: Handling Missing Data

**Q7.** Given the following DataFrame with missing values, fill the missing values with 0.
```python
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
```

In [89]:
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
copyy = df_nan.copy()
copyy.fillna(0)

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

**Q8.** Drop the rows containing any missing values in `df_nan`.

In [90]:
print(copyy.dropna())

     A    B
0  1.0  4.0

## Practice 5: Grouping and Aggregation

**Q9.** Group the following DataFrame by 'Department' and calculate the mean salary.
```python
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
```

In [91]:
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
df_emp.groupby("Department").mean()

             Salary
Department
Finance     80000.0
HR          52500.0
IT          65000.0

## Practice 6: Adding and Removing Columns

**Q10.** Add a new column 'Bonus' to `df_emp` which is 10% of the 'Salary'.

In [92]:
copyyy=df_emp.copy()
copyyy["Bonus"] = copyyy["Salary"] * 0.1
copyyy.head(10)

  Department  Salary   Bonus
0         IT   60000  6000.0
1         HR   50000  5000.0
2         IT   70000  7000.0
3    Finance   80000  8000.0
4         HR   55000  5500.0

**Q11.** Drop the 'Bonus' column from `df_emp`.

In [93]:
copyyy=copyyy.drop(columns=["Bonus"])
copyyy.head(10)

  Department  Salary
0         IT   60000
1         HR   50000
2         IT   70000
3    Finance   80000
4         HR   55000

## Practice 7: Applying Functions

**Q12.** Apply a function or a lambda to convert the 'Department' names to lowercase in `df_emp`.

In [94]:
df_empp = df_emp.copy()
df_empp["Department"] = df_empp["Department"].map(str.lower)
df_empp.head

<bound method NDFrame.head of   Department  Salary
0         it   60000
1         hr   50000
2         it   70000
3    finance   80000
4         hr   55000>

## Practice 8: Merging and Joining

**Q13.** Create a DataFrame `df_dept` with columns `Department` and `Manager` mapping 'IT' to 'Alice', 'HR' to 'Bob', and 'Finance' to 'Charlie'. Merge it with `df_emp` (from Practice 5) using a left join.

In [95]:
df_dept = pd.DataFrame({'Department': ['IT', 'HR', 'Finance'], 'Manager': ['Alice', 'Bob', 'Charlie']})
left_join = pd.merge(
    df_dept, df_emp, on="Department", how="left"
)
left_join.head(10)

  Department  Manager  Salary
0         IT    Alice   60000
1         IT    Alice   70000
2         HR      Bob   50000
3         HR      Bob   55000
4    Finance  Charlie   80000

## Practice 9: Pivot Tables

**Q14.** Create a pivot table from the merged DataFrame that shows the total (sum) and average (mean) salary for each manager.

In [96]:
pivot_table_df = left_join.pivot_table(
    values='Salary', 
    index='Manager', 
    aggfunc=['sum', 'mean']
)
pivot_table_df

            sum     mean
         Salary   Salary
Manager
Alice    130000  65000.0
Bob      105000  52500.0
Charlie   80000  80000.0

## Practice 10: Advanced Data Manipulation

**Q15.** Given a DataFrame with sales data, calculate the rolling 3-day average of 'Revenue'.
```python
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
```

In [97]:
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
df_sales['Rolling_3Day_Avg'] = df_sales['Revenue'].rolling(window=3).mean()
df_sales.head(20)

        Date Product  Revenue  Rolling_3Day_Avg
0 2023-01-01       A      100               NaN
1 2023-01-02       B      200               NaN
2 2023-01-03       A      150        150.000000
3 2023-01-04       B      250        200.000000
4 2023-01-05       A      300        233.333333
5 2023-01-06       A      250        266.666667
6 2023-01-07       B      100        216.666667
7 2023-01-08       B      150        166.666667
8 2023-01-09       A      200        150.000000
9 2023-01-10       B      300        216.666667

**Q16.** Find the top 2 highest revenue days for each product from `df_sales`.

In [98]:
df_sales=df_sales.sort_values("Revenue", ascending=False)
df_sales=df_sales.sort_values("Product")
df_sales.groupby("Product").head(2)

        Date Product  Revenue  Rolling_3Day_Avg
4 2023-01-05       A      300        233.333333
5 2023-01-06       A      250        266.666667
9 2023-01-10       B      300        216.666667
3 2023-01-04       B      250        200.000000

In [99]:
########## OR #####################################
print(df_sales[df_sales["Product"] == "A"].iloc[0:2])
print(df_sales[df_sales["Product"] == "B"].iloc[0:2])

        Date Product  Revenue  Rolling_3Day_Avg
4 2023-01-05       A      300        233.333333
5 2023-01-06       A      250        266.666667
        Date Product  Revenue  Rolling_3Day_Avg
9 2023-01-10       B      300        216.666667
3 2023-01-04       B      250        200.000000

**Q17.** Extract the year and month from the 'Date' column in `df_sales` and create two new columns 'Year' and 'Month'.

In [100]:
df_sales=df_sales.sort_index()
df_sales['Year'] = df_sales['Date'].dt.year
df_sales['Month'] = df_sales['Date'].dt.month
df_sales.sample(10)

        Date Product  Revenue  Rolling_3Day_Avg  Year  Month
7 2023-01-08       B      150        166.666667  2023      1
4 2023-01-05       A      300        233.333333  2023      1
2 2023-01-03       A      150        150.000000  2023      1
3 2023-01-04       B      250        200.000000  2023      1
6 2023-01-07       B      100        216.666667  2023      1
5 2023-01-06       A      250        266.666667  2023      1
9 2023-01-10       B      300        216.666667  2023      1
1 2023-01-02       B      200               NaN  2023      1
0 2023-01-01       A      100               NaN  2023      1
8 2023-01-09       A      200        150.000000  2023      1